spring.application.name=cafeOn

# ===============================
# Database Connection Settings
# ===============================
spring.datasource.url=jdbc:mysql://${DB_URL}:3306/cafeOn?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# S3 Connection Settings
# ===============================
cafeon.cdn-base-url=${CDN_BASE_URL:https://b1a4-cafeon.s3.amazonaws.com/}
spring.cloud.aws.region.static=${AWS_REGION}
spring.cloud.aws.s3.bucket=${AWS_S3_BUCKET}
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_KEY}

# ===============================
# JPA / Hibernate SQL \uB85C\uADF8 + \uD30C\uB77C\uBBF8\uD130 \uCD9C\uB825
# ===============================
spring.jpa.hibernate.ddl-auto=update
    # \uC774\uBBF8 \uD14C\uC774\uBE14\uC774 \uC788\uB2E4\uBA74 validate \uAD8C\uC7A5\uD55C\uB300\uC694, \uADFC\uB370 \uAC1C\uBC1C \uC911\uC5D0 Entity \uC218\uC815\uC5D0 \uB530\uB77C \uD14C\uC774\uBE14\uB3C4 \uC790\uB3D9\uC73C\uB85C \uBC14\uB00C\uAE38 \uC6D0\uD55C\uB2E4\uBA74 update\uAC00 \uB9DE\uB300\uC694!
spring.jpa.show-sql=true
    # \uC2E4\uD589\uB418\uB294 SQL \uBCF4\uC5EC\uC8FC\uAE30
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


# ===============================
# JWT
# ===============================
# \uC774\uC288 \uBC1C\uAE09\uC790
jwt.issuer=team_b1a4-cafeOnProject
# \uBE44\uBC00\uD0A4
jwt.secret_key=${JWT_SECRET_KEY}


# ===============================
# Swagger UI / OpenAPI \uC124\uC815
# ===============================
# Swagger UI \uC811\uC18D \uACBD\uB85C (\uAE30\uBCF8: /swagger-ui/index.html)
springdoc.swagger-ui.path=/api-docs

# OpenAPI JSON \uBB38\uC11C \uACBD\uB85C (\uAE30\uBCF8: /v3/api-docs)
#springdoc.api-docs.path=/api-docs-json

# \uBB38\uC11C \uAE30\uBCF8 \uC815\uBCF4
springdoc.swagger-ui.operationsSorter=method
    # \uBA54\uC11C\uB4DC(GET/POST \uB4F1) \uAE30\uC900 \uC815\uB82C
springdoc.swagger-ui.tagsSorter=alpha
    # \uD0DC\uADF8 \uC54C\uD30C\uBCB3\uC21C \uC815\uB82C

# API info (\uC81C\uBAA9, \uC124\uBA85, \uBC84\uC804)
springdoc.api-docs.version=openapi-3.0
springdoc.show-actuator=true

# ===============================
# Mail Settings (\uC784\uC2DC \uBE44\uBC00\uBC88\uD638 \uBC1C\uC1A1\uC6A9)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
    # TLS \uBC29\uC2DD(\uBCF4\uC548 \uC5F0\uACB0)\uC5D0\uC11C \uC0AC\uC6A9\uD558\uB294 \uD3EC\uD2B8 \uBC88\uD638. Gmail\uC5D0\uC11C\uB294 587\uC774 \uC77C\uBC18\uC801
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# Spring Boot \uB85C\uADF8 \uCEEC\uB7EC \uD65C\uC131\uD654
spring.output.ansi.enabled=always

# Kakao API key \uAC00\uC838\uC624\uAE30
kakao.api.key=${KAKAO_API_KEY}

# \uD30C\uC77C \uC5C5\uB85C\uB4DC \uACBD\uB85C \uC124\uC815
file.upload-dir=C:/cafeon/uploads/posts/

# \uCD5C\uB300 \uD30C\uC77C \uD06C\uAE30 \uC81C\uD55C \uC124\uC815 (\uAC1C\uBCC4 \uD30C\uC77C)
spring.servlet.multipart.max-file-size=10MB

# \uC804\uCCB4 \uC694\uCCAD \uD06C\uAE30 \uC81C\uD55C \uC124\uC815
spring.servlet.multipart.max-request-size=10MB