spring.application.name=cafeOn

# ===============================
# Database Connection Settings
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/cafeOn?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate Settings
# ===============================

spring.jpa.hibernate.ddl-auto=update
    # \uC774\uBBF8 \uD14C\uC774\uBE14\uC774 \uC788\uB2E4\uBA74 validate \uAD8C\uC7A5\uD55C\uB300\uC694, \uADFC\uB370 \uAC1C\uBC1C \uC911\uC5D0 Entity \uC218\uC815\uC5D0 \uB530\uB77C \uD14C\uC774\uBE14\uB3C4 \uC790\uB3D9\uC73C\uB85C \uBC14\uB00C\uAE38 \uC6D0\uD55C\uB2E4\uBA74 update\uAC00 \uB9DE\uB300\uC694!
spring.jpa.show-sql=true
    # \uC2E4\uD589\uB418\uB294 SQL \uBCF4\uC5EC\uC8FC\uAE30
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ===============================
# JWT
# ===============================
# \uC774\uC288 \uBC1C\uAE09\uC790
jwt.issuer=team_b1a4-cafeOnProject
# \uBE44\uBC00\uD0A4
jwt.secret_key=sesac-ydp7-final-project-cafeOn-secretkey


# ===============================
# Swagger UI / OpenAPI \uC124\uC815
# ===============================

# Swagger UI \uC811\uC18D \uACBD\uB85C (\uAE30\uBCF8: /swagger-ui/index.html)
springdoc.swagger-ui.path=/api-docs

# OpenAPI JSON \uBB38\uC11C \uACBD\uB85C (\uAE30\uBCF8: /v3/api-docs)
#springdoc.api-docs.path=/api-docs-json

# \uBB38\uC11C \uAE30\uBCF8 \uC815\uBCF4
springdoc.swagger-ui.operationsSorter=method
    # \uBA54\uC11C\uB4DC(GET/POST \uB4F1) \uAE30\uC900 \uC815\uB82C
springdoc.swagger-ui.tagsSorter=alpha
    # \uD0DC\uADF8 \uC54C\uD30C\uBCB3\uC21C \uC815\uB82C

# API info (\uC81C\uBAA9, \uC124\uBA85, \uBC84\uC804)
springdoc.api-docs.version=openapi-3.0
springdoc.show-actuator=true


# Spring Boot \uB85C\uADF8 \uCEEC\uB7EC \uD65C\uC131\uD654
spring.output.ansi.enabled=always