spring.application.name=cafeOn

# ===============================
# Database Connection Settings
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/cafeOn?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate Settings
# ===============================

spring.jpa.hibernate.ddl-auto=update
    # 이미 테이블이 있다면 validate 권장한대요, 근데 개발 중에 Entity 수정에 따라 테이블도 자동으로 바뀌길 원한다면 update가 맞대요!
spring.jpa.show-sql=true
    # 실행되는 SQL 보여주기
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ===============================
# Swagger UI / OpenAPI 설정
# ===============================

# Swagger UI 접속 경로 (기본: /swagger-ui/index.html)
springdoc.swagger-ui.path=/api-docs

# OpenAPI JSON 문서 경로 (기본: /v3/api-docs)
#springdoc.api-docs.path=/api-docs-json

# 문서 기본 정보
springdoc.swagger-ui.operationsSorter=method
    # 메서드(GET/POST 등) 기준 정렬
springdoc.swagger-ui.tagsSorter=alpha
    # 태그 알파벳순 정렬

# API info (제목, 설명, 버전)
springdoc.api-docs.version=openapi-3.0
springdoc.show-actuator=true